---
- name: Play 1
  hosts: all
  tasks:
      - name: Task 1.1
        debug:
            msg: Task 1.1

      - name: Task 1.2
        debug:
            msg: Task 1.2

- name: Play 2
  hosts: all
  tasks:
      - name: Task 2.1
        debug:
            msg: Task 2.1

      - name: Task 2.2
        debug:
            msg: Task 2.2

- name: Show network details
  hosts: all
  gather_facts: no
  tasks:
      - name: Show IP addresses
        command: ip addr show
        register: ip_addresses

      - name: Display IP addresses
        debug:
            var: ip_addresses.stdout_lines

      - name: Show routing table
        command: ip route show
        register: routing_table

      - name: Display routing table
        debug:
            var: routing_table.stdout_lines

- name: Show execution environment details
  hosts: all
  gather_facts: yes
  tasks:
      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display Ansible version
        command: ansible --version
        register: ansible_version

      - name: Display Ansible version output
        debug:
            var: ansible_version.stdout_lines
