---
- name: Play 1
  hosts: all
  tasks:
      - name: Task 1.1
        debug:
            msg: Task 1.1

      - name: Task 1.2
        debug:
            msg: Task 1.2

- name: Play 2
  hosts: all
  tasks:
      - name: Task 2.1
        debug:
            msg: Task 2.1

      - name: Task 2.2
        debug:
            msg: Task 2.2

- name: Show execution environment details
  hosts: all
  gather_facts: yes
  tasks:
      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display host information
        debug:
            var: hostvars[inventory_hostname]

      - name: Display Ansible version
        command: ansible --version
        register: ansible_version

      - name: Display Ansible version output
        debug:
            var: ansible_version.stdout_lines

- name: Collect host details
  hosts: all
  gather_facts: true
  tasks:
    - name: Collect system information
      command: "uname -a"
      register: system_info
    - name: Collect CPU information
      command: "lscpu"
      register: cpu_info
    - name: Collect memory information
      command: "free -m"
      register: memory_info
    - name: Collect disk information
      command: "df -h"
      register: disk_info
    - name: Print host information
      debug:
        var: hostvars[inventory_hostname]
    - name: Print system information
      debug:
        var: system_info
    - name: Print CPU information
      debug:
        var: cpu_info
    - name: Print memory information
      debug:
        var: memory_info
    - name: Print disk information
      debug:
        var: disk_info
        
- name: Show network details
  hosts: all
  gather_facts: no
  tasks:
      - name: Show IP addresses
        command: ip addr show
        register: ip_addresses

      - name: Display IP addresses
        debug:
            var: ip_addresses.stdout_lines

      - name: Show routing table
        command: ip route show
        register: routing_table

      - name: Display routing table
        debug:
            var: routing_table.stdout_lines
